services:
  app:
    build: .
    container_name: milktea-app
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.milktea.rule=Host(`demo-milktea.zoskisk.com`)"
      - "traefik.http.routers.milktea.entrypoints=websecure"
      - "traefik.http.services.milktea.loadbalancer.server.port=3000"
      - "traefik.http.routers.milktea.tls.certresolver=letsencrypt"
    networks:
      - traefik_default
    volumes:
      - ./data.db:/app/data.db

networks:
  traefik_default:
    external: true